pipeline {
    agent any

    tools {
        maven 'M3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/chris-zano/qa-demo.git'
            }
        }
        stage('Test') {
            steps {
                sh 'cd demo'
                sh 'mvn clean test'
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
        }
        success {
            emailext(
                to: 'cncs.chris@gmail.com',
                subject: "Jenkins Build #${env.BUILD_NUMBER} Succeeded",
                body: """
                Hello Team,

                The Jenkins build for *${env.JOB_NAME}* has completed successfully.

                Build Number: ${env.BUILD_NUMBER}
                Build URL: ${env.BUILD_URL}

                Regards,
                Jenkins
                """,
                mimeType: 'text/plain'
            )
        }
        failure {
            emailext(
                to: 'cncs.chris@gmail.com',
                subject: "Jenkins Build #${env.BUILD_NUMBER} Failed",
                body: """
                Hello Team,

                The Jenkins build for *${env.JOB_NAME}* has failed.

                Build Number: ${env.BUILD_NUMBER}
                Build URL: ${env.BUILD_URL}

                Please investigate the failure.

                Regards,
                Jenkins
                """,
                mimeType: 'text/plain'
            )
        }
    }
}
